export const SAVE_EMPLOYEE_REQUEST = 'UpdateEmployee/SAVE_CHANGE_REQUEST';
export const SAVE_EMPLOYEE_SUCCESS = 'UpdateEmployee/SAVE_CHANGE_SUCCESS';
export const SAVE_EMPLOYEE_ERROR = 'UpdateEmployee/SAVE_CHANGE_ERROR';
export const LOAD_EMPLOYEE_LIST_REQUEST = 'ListEmployee/SAVE_CHANGE_REQUEST';
export const LOAD_EMPLOYEE_LIST_SUCCESS = 'ListEmployee/SAVE_CHANGE_SUCCESS';
export const LOAD_EMPLOYEE_LIST_ERROR = 'ListEmployee/SAVE_CHANGE_FAILURE';
