// Auth
export const LOGIN_WITH_USERNAME_PASSWORD = 'APP/LOGIN_WITH_USERNAME_PASSWORD';
export const LOGIN_BEGIN = 'APP/LOGIN_BEGIN';
export const LOGIN_SUCCESS = 'APP/LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'APP/LOGIN_FAILURE';
export const LOGOUT = 'APP/LOGOUT';
export const LOGOUT_UNAUTHORIZED = 'APP/LOGOUT_UNAUTHORIZED';
